apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: idea-api
spec:
  replicas: 1
  podManagementPolicy: "Parallel"
  serviceName: "idea-api"
  selector:
    matchLabels:
      app: idea-api
  template:
    metadata:
      labels:
        app: idea-api
    spec:
#      serviceAccountName: oedp-sa
      terminationGracePeriodSeconds: 60
      containers:
        - name: idea-api
          image: eventdrivendev01.aws.io/idea-api:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: 1
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://database-1.crgf0knajwzv.us-east-1.rds.amazonaws.com:5432/ideaportal"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update

          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
